### ISSUE TITLE
Runtime error in CKKS bootstrapping and Question for Default Parameters

### ISSUE THREAD

**Issue by joonwoolee42** [ldsec/lattigo#155]
Hello, I am Joon-Woo Lee at Seoul National University. I cloned the master branch and tried to perform the non-sparse bootstrapping with parameter VI. However, it showed a run-time error. I did not change anything except the ckksParams and btpParams are set with bootstrapping.DefaultCKKSParameters[3] and bootstrapping.DefaultParameters[3], respectively. Is it the right way to perform the non-sparse bootstrapping with secret key hamming weight 32768?
![image](https://user-images.githubusercontent.com/66359100/141079632-f8959b8b-49cd-4117-aa18-80b33cfe12e9.png)

I also have a question about the default parameters. The default parameters you enumerated in your code include all RNS primes in the modulus, but I thought it is enough to put the length of each prime as input (logQ or logP). Indeed, your enumerated primes are somewhat different from the primes generated by GenModuli, that is, the level zero modulus is somewhat different. I want to ask why you enumerate all the primes rather than just specifying the values of logQ and logP. Thanks for reading my question!

**Comment by Pro7ech** [comment]
Hi Joon, 

Thank you for your feedback. I have identified the error, it comes from a bad handling of odd/even optimized polynomial evaluation. I will fix it today. You can use the branch `dev_paper` in the mean time, which is the official branch that was used to generate the results showcased in our work. 

About the primes, since those are default parameters, we wanted to have hard coded primes, so that if how our primes are generated would change, the default parameters would remain the same. I also observed that the order of the primes has a slight effect on the final precision. I tried several other ordering (including the default one), as well as other prime generation technique (such as the one of [KPP20](https://eprint.iacr.org/2020/1118), but they all lead to worse results. I have no explanation for this behavior.

**Comment by joonwoolee42** [comment]
Thanks for your answer and for fixing the bug, and I really appreciate your answer.
