### ISSUE TITLE
Clarification about collective key switching

### ISSUE THREAD

**Issue by jon-chuang** [ldsec/lattigo#32]
I don't understand why collective key switching must be performed rather than generating keyswitch keys.

Can't a similar procedure be used to generating relinearisation keys collectively? 

This approach seems to introduce unnecessary communication costs.

Furthermore, there does not seem to be a description of how galois keys can be generated. However, can't one generate Galois keys by just permuting the coefficients of the secret key? This is not a problem even if we are dealing with shared secrets. So it is easy to publish galois keys, is it not? What other purpose is there for collective key switching?

**Comment by Pro7ech** [comment]
Hello Jon-Chuang, 

Yes you are right, the parties could also generate in advance a keyswitching key and have someone else carry the operation using only public operations. Using such an approach does however introduces a larger noise amount than just having each party partialy re-encrypt the ciphertext. There are pros and cons for each approaches.

The galois keys are an encryption of a permutation of the coefficients of the collective secret-key, so yes they are as "easy" to generate as the collective public-key.

What do you mean by "What other purpose is there for collective key switching?" ?

**Comment by ChristianMct** [comment]
To add up to @Pro7ech 's answer, the CKS protocol enables the parties to allow decryption or, re-encryption under the receiver's key, of the computation result (and only the computation result) to be performed. Indeed, this needs to be an interactive functionality (because of @Pro7ech's Edit1).

So, in our terminology, we differentiate the notions of key-switching (s1 -> s2) and relinearization (s^2 -> s).

**Comment by jon-chuang** [comment]
Hi all, I understand this better.

Essentially, collective keyswitching is meant as a barrier so that the parties who have a stake in the data can collectively agree to allow a single party to decrypt the data, even if they do not know the secret key of that party (PCKS), or that party has shared it with them collectively through secret sharing (CKS).

However, I still feel there is a missing piece of the puzzle, which is zero knowledge. This would incur some overhead (100x?) but may be what an application developer wants to have more control over their data.

**Comment by ChristianMct** [comment]
You are correct about the need for ZK primitives when more guarantees are needed and we would be happy to push this discussion further. As for the HE scheme you are proposing, this seems like an interesting path to investigate. However, since it does not concern the code-base directly, please use the Lattigo mailing list: lattigo@listes.epfl.ch.

**Comment by ChristianMct** [comment]
Closing: discussion taken offline.

**Comment by jon-chuang** [comment]
The above scheme I described does not exist, as I just figured out today. 

Hence I think zero knowledge is the only viable alternative we known of.
