### ISSUE TITLE
Default Parameters 

### ISSUE THREAD

**Issue by AmitKawad** [ldsec/lattigo#48]
In version 1.1.0 of the library, can I use the parameters apart from default parameters that correspond to 128-bit security. 
The default parameters start from 4096. can I use 1024 instead and how ?
{4096, 65537, logN12Q109, Pi60[len(Pi60)-len(logN12Q109)-1:], 3.19
what will I need to update apart from 4096 in the above parameter

**Comment by ChristianMct** [comment]
Hi @AmitKawad, 

It is unfortunately not possible to use small parameter set in the `v1.1.0`. 
However, we will introduce this feature in the `v1.4.0`, which is accessible on the `dev_v1.4.0` branch.

Note that, since `v1.3.0`, it is easier to instantiate the parameters by specifying their sizes:
```
params := &Parameters{LogN: 11,
		T: 12289,
		LogModuli: LogModuli{
		LogQi:    []uint64{54},
		LogPi:    []uint64{},
		LogQiMul: []uint64{60},
	},
	Sigma: 3.2}

params.GenFromLogModuli()
```
But the above will not work on `v1.3.0` because of this version does not handle the case where there is no extended basis QP (`LogPi:    []uint64{}`).

Also note that `LogN: 10` does not enable NTT in the plaintext space and we are still discussing whether we would like to support it.

Hope this helps!
