### ISSUE TITLE
bootstrapping more than once problem

### ISSUE THREAD

**Issue by vidstrancar** [ldsec/lattigo#72]
Hi, 
i transitioned to this library from SEAL because of CKKS bootstrapping.
For starters I just wrote one ciphertext - ciphertext multiplication, then rescale then bootstrapping and it worked fine, meaning the
result after bootstrapping was good enough.
Then I tested two bootstraps in the row: ciphertext - ciphertext multiplication, rescaling, bootstrapping and again on resulting ciphertext: ciphertext - ciphertext multiplication, rescaling, bootstrapping and result is very much off.

Pseudocode: 
ciphertext1 = Enc([1.0, 1.0, ..., 1.0])
ciphertext2 = Enc([3.0, 3.0, ..., 3.0])
ciphertext1 = ciphertext1 * ciphertext2
evaluator.SetScale(ciphertext1, params.scale())
ciphertext1 = bootstrapper(ciphertext1)
ciphertext1 = ciphertext1 * ciphertext2
evaluator.SetScale(ciphertext1, params.scale())
ciphertext1 = bootstrapper(ciphertext1)

Code: https://pastebin.pl/view/b6cffc02

Output:
CKKS parameters: logN = 16, logSlots = 15, logQP = 1521, levels = 25, scale= 2^45.000000, sigma = 3.200000 
ciphertext1 fresh (level/scale):  24 45
ciphertext1 after multiplication (level/scale):  24 90
plaintext after multiplication:  (3.000000150894784-2.707561827248977e-08i)
ciphertext1 after setScale (level/scale):  23 45
plaintext after setScale:  (3.000000151844232-2.71851598944193e-08i)
ciphertext1 after bootstrapping (level/scale):  10 45
plaintext after bootstrapp:  (2.9998322935427497+1.2314033711896221e-06i)

ciphertext1 after multiplication (level/scale):  10 90
plaintext after multiplication:  (8.999496993467984+3.6738101362829465e-06i)
ciphertext1 after setScale (level/scale):  8 45
plaintext after setScale:  (4.64277915039133e-11+1.7291085069162014e-11i)
ciphertext1 after bootstrapping (level/scale):  10 45
plaintext after bootstrapp:  (-2.5712217415452037e-08+3.0729998052670696e-06i)

So, it seems like everything is fine until second SetScale where ciphertext suddenly drops two level instead of one.

On another note, how to setup small parameters to fasten up bootstrapping, completely disregarding security. Its very counter-productive that i have to wait for so long everytime i run some tests of bootstrapping?

**Comment by Pro7ech** [comment]
Hi vidstrancar, 

First, thank you very much for providing the code, it helped a lot find out what is going on. 

All that needs to be done to make your code work is replace 

`evaluator.SetScale(ciphertext1, params.Scale())`

by

`evaluator.Rescale(ciphertext1, params.Scale(), ciphertext1)`

Indeed, the primary way of managing the scale with Lattigo is the evaluator.Rescale(*) method, which divides the ciphertext by the next modulus in the moduli scale.

On the other hand, evaluator.SetScale(*) aims at changing the scale of a ciphertext to an other scale that is very close (ex, your scale is close to a power of two and you want to make it change to that power of two). It will multiply the ciphertext by the integer round((target_scale * qi)/ciphertext_scale) where qi is the next modulus in the moduli chain, and then divide by qi. If ciphertext_scale >> target_scale * qi, then the value becomes zero and all the values of the ciphertext are set to zero. Hence this method shouldn't be used on a ciphertext that is not yet rescaled. The behavior of this method is not well documented, and we will update that.

**Comment by vidstrancar** [comment]
Just replacing SetScale with Rescale in my code resulted in a crash (exit status 2, whatever that means...), but according to the comment in the ckks bootstrapp example you provide, there is a line in comments that says: "// To equalize the scale, the function evaluator.SetScale(ciphertext, parameters.Scale) can be used at the expense of one level."	

So, keeping your answer in mind, i tried to use .rescale() first and then .setScale() and it worked, the result after second bootstrapping is correct! that's awesome :D 

Does that mean, that i should always use .Rescale(...) first and then use .SetScale(...) whenever rescaling?

And also, on the second part of my question: what would be good parameters to speed up bootstrapping, i dont care about security, because im just playing around testing the capabilities of library?

**Comment by vidstrancar** [comment]
One more comment on the Rescale + setScale method: it takes away two levels instead of just one.
In SEAL rescaling was done like this: evaluator.rescale(ciphertext), to get ciphertext scale close to params.scale with modulus switch and then simply, ciphertext.scale = params.scale. this method took only one level away. 
Should i do the same in lattigo or should i use rescale + setScale method?

And also, i added third round of multiplications (https://pastebin.com/pAFFDY5V) and it works fine-ish.
i get the following output: 
CKKS parameters: logN = 16, logSlots = 15, logQP = 1521, levels = 25, scale= 2^45.000000, sigma = 3.200000 
ciphertext1 fresh (level/scale):  24 45
ciphertext1 after multiplication (level/scale):  24 90
plaintext after multiplication:  (3.000000133556691-6.491486321861562e-10i)
ciphertext1 after rescale (level/scale):  24 90
plaintext after rescale:  (3.000000133556691-6.491486321861562e-10i)
ciphertext1 after setScale (level/scale):  23 45
plaintext after setScale:  (3.000000134576702-6.156673925673252e-10i)
ciphertext1 after bootstrapping (level/scale):  10 45
plaintext after bootstrapp:  (2.999830465062783+3.64803886812801e-06i)

ciphertext1 after multiplication (level/scale):  10 90
plaintext after multiplication:  (8.999491495278939+1.0943606103172461e-05i)
ciphertext1 after rescale (level/scale):  9 44.99999963991133
plaintext after rescale:  (8.999491495264994+1.0943745458555484e-05i)
ciphertext1 after setScale (level/scale):  8 45
plaintext after setScale:  (8.999491495105095+1.0943685243493157e-05i)
ciphertext1 after bootstrapping (level/scale):  10 45
plaintext after bootstrapp:  (8.994918788405583+1.9186356095265893e-05i)

ciphertext1 after multiplication (level/scale):  10 90
plaintext after multiplication:  (26.984756665335944+5.7557537835505303e-05i)
ciphertext1 after rescale (level/scale):  9 44.99999963991133
plaintext after rescale:  (26.984756665218107+5.755755109137134e-05i)
ciphertext1 after setScale (level/scale):  8 45
plaintext after setScale:  (26.984756665219308+5.755755574364474e-05i)
signal: killed

You see, the result is correct, but im wondering what's that "signal: killed" at the end. Does that mean that my computer ran out of resources? That doesn't make sense really, as just about anything resources-heavy is already complete at that point.

I thank you very much in advance for your patience and very valuable input.

**Comment by Pro7ech** [comment]
When I repalce setscale by rescale the code works fine for me. You should not set-scale after you rescale. Those two methods do not fulfill the same purpose. Rescale's purpose is to manage the magnitude of the plaintext scale, while set-scale's purpose is to manage the of the scale deviation from the original power of two scale or to change it to something close. In a circuit, you can always include a set-scale "for free", either in a linear transformation or a polynomial evaluation (unless if it is a monic polynomial), by scaling the plaintext/coefficients accordingly (this is what is done in our bootstrapp), so you should try to avoid this method whenever possible.

You do not need to bootstrapp after every ciphertext multiplication (those parameters allow for a circuit of depth 10 after each bootstrapp). However, your error is probably due to a memory management problem from Go (we observed that Go sometime does not call the garbage collector when it should), try forcing it by importing "runtime" and calling runtime.GC() after the bootstrapp

**Comment by vidstrancar** [comment]
If i simply replace setscale by rescale (https://pastebin.com/U9Uk2sJ3) i get following error during bootstrapping:
KKS parameters: logN = 16, logSlots = 15, logQP = 1521, levels = 25, scale= 2^45.000000, sigma = 3.200000 

ciphertext1 fresh (level/scale):  24 45
ciphertext1 after multiplication (level/scale):  24 90
plaintext after multiplication:  (3.0000001668388347+1.6261240919556596e-08i)
ciphertext1 after rescale (level/scale):  24 90
plaintext after rescale:  (3.0000001668388347+1.6261240919556596e-08i)
panic: runtime error: index out of range [24] with length 24

goroutine 1 [running]:
github.com/ldsec/lattigo/v2/ring.(*Ring).MulCoeffsMontgomeryLvl(0xc0000e8d80, 0x18, 0xc42fbc8600, 0xc57098eb80, 0xc3cd6678c0)
	/home/vid/homomorphic/lattigo/ring/ring_operations.go:439 +0x284
github.com/ldsec/lattigo/v2/ckks.(*Bootstrapper).multiplyByDiagMatrice(0xc3df558000, 0xc00000e070, 0xc3cd667ea0, 0xc00000e070)
	/home/vid/homomorphic/lattigo/ckks/bootstrapp.go:264 +0x9af
github.com/ldsec/lattigo/v2/ckks.(*Bootstrapper).dft(0xc3df558000, 0xc00000e070, 0xc3cd667a40, 0x4, 0x4, 0xc0000b5a01, 0x518c47)
	/home/vid/homomorphic/lattigo/ckks/bootstrapp.go:168 +0x73
github.com/ldsec/lattigo/v2/ckks.(*Bootstrapper).coeffsToSlots(0xc3df558000, 0xc00000e050, 0xc00000e050, 0xc00000e050)
	/home/vid/homomorphic/lattigo/ckks/bootstrapp.go:117 +0x7d
github.com/ldsec/lattigo/v2/ckks.(*Bootstrapper).Bootstrapp(0xc3df558000, 0xc00000e050, 0xc0000b5d60)
	/home/vid/homomorphic/lattigo/ckks/bootstrapp.go:39 +0x1cc
main.main()
	/home/vid/homomorphic/lattigo/examples/ckks/product-simple/main.go:77 +0xf97
exit status 2

**Comment by Pro7ech** [comment]
This is because the input scale to the bootstrapp is 2^{90}, which is more than Q0/2^{10}. This is fixed in one of the PR, so it should not affect you once it is merged. It is happening because you try to rescale with a 53bit moduli a scale of 2^{90}, which would make it go under the target 2^{45} that you give, so it does not rescale and returns an error.

If you encode the ciphertext at the max level, you either need to construct a circuit that can re-use the moduli of the bootstrapp circuit, or drop the levels of the ciphertext to the level after the bootstrapp (here 10) by calling : 

```
for ciphertext1.Level() != 10{
	evaluator.DropLevel(ciphertext1, 1)
}
```

Initial values 24 45.000000 1.000000 1.000000 1.000000 1.000000

Iteration n° 0
After Mul            : 10 90.000000 3.000000 3.000000 3.000000 3.000000
After Rescale       :  9 45.000000 3.000000 3.000000 3.000000 3.000000
After SetScale      :  8 45.000000 3.000000 3.000000 3.000000 3.000000
After Bootstrapp : 10 45.000000 2.999832 2.999829 2.999830 2.999831

Iteration n° 1
After Mul            : 10 90.000000 8.999496 8.999486 8.999489 8.999494
After Rescale       :   9 45.000000 8.999496 8.999486 8.999489 8.999494
After SetScale      :   8 45.000000 8.999496 8.999486 8.999489 8.999494
After Bootstrapp : 10 45.000000 8.994923 8.994913 8.994913 8.994920

Iteration n° 2
After Mul            : 10 90.000000 26.984770 26.984738 26.984740 26.984760
After Rescale       :   9 45.000000 26.984770 26.984738 26.984740 26.984760
After SetScale      :   8 45.000000 26.984770 26.984738 26.984740 26.984760
After Bootstrapp : 10 45.000000 26.861638 26.861611 26.861603 26.861627

**Comment by vidstrancar** [comment]
Okay thanks, i think i got it.
