### ISSUE TITLE
Less levels needed when bootstrapping

### ISSUE THREAD

**Issue by vidstrancar** [ldsec/lattigo#76]
Hi.
So I tried implementing max function, which returns approximate maximum among ciphertext.slots() real numbers from interval [0,1 ] encoded and encrypted in single ciphertext. To do this I first implement approximate max(a,b) = (a + b + abs(a-b))/2, where i approximate abs(x) = sqrt_cheby(x^2), where sqrt_cheby is cheby approximation of sqrt on [0, 1] of degree 33. With max(a, b) implemented I rotate log2(ciphertext.slots) times. In each iteration i calculate ciphertext = max(ciphertext, rotate(ciphertext, 2^i)). All of this costs 10 levels, so i bootstrapp in each iteration.
This works fine and among ciphertext.slots real numbers from interval [0, 1] i get approximate max which is three decimals accurate
which is good enough for me, as this was just an experiment and not a serious attempt.
By choosing default bootstrapp parameters  I get 24 levels on fresh ciphertext, but that is too much since i only need 11. Those 13 excessive levels increase the size of ciphertext but more importantly probably slow down the whole bootstrapp operation. So my question is how to choose parameters for encryption and bootstrapping with only 11 levels on fresh ciphertext?
(the code is here https://pastebin.com/gug4N4Tg, but due to all the Printlns looks like shit. Consider yourself warned :) )

**Comment by Pro7ech** [comment]
Hello vidstrancar, 

Thank you for your interest in our library. I'll do my best to clarify how to use the bootstrapping in the scope of your project. 
The CKKS bootstrapping takes a ciphertext at level 0 and re-encrypts it at a level _L_-_k_ where _L_ is the max level and _k_ is the depth of the bootstrapping. You can then use the _L_-_k_ levels that are left to carry out homomorphic operations, until you reach the levle 0 and needs to bootstrapp again. 

Hence, those 24 levels are in a way required, because the bootstrapping will consume a large amount of those levels, and you can effectively use only what is left after.

When you encrypt first, you have several choices : 

- You can use the bootstrapping parameters, encrypt at the max level and use "for free" the moduli chain of the bootstrapping. Unfortunately, I don't think the library let you yet encrypt at a specific level to avoid having to encrypt at the max level. But this can be sorted with the next option.

- You can use other parameters, but with at least the same Q0 (first modulus) or the same moduli chain but without the bootstrapping moduli chain, encrypt with those parameters, evaluate some circuit, and then bootstrapp when you reach the level 0.
